// src/preact/components/Footnotes/index.jsx
/* eslint-disable no-unused-vars */
import { h } from 'preact';

import Footnote from '../Footnote';

import style from './style.module.css';

export default function Footnotes({ footnotes }) {
	return (
		<ol class={style.footnotes}>
			{footnotes.map(footnote => {
				return <Footnote key={footnote.id} footnote={footnote} />;
			})}
		</ol>
	);
}

// src/vue/components/Footnotes/index.vue
<script setup>

	import Footnote from '../Footnote/index.vue';

	import style from './style.module.css';

	defineProps({
		footnotes: {
			type: Array,
			required: true
		}
	});

</script>

<template>
	<ol :class="style.footnotes">
		<template v-for="footnote in footnotes" :key="footnote.id">
			<Footnote :footnote="footnote" />
		</template>
	</ol>
</template>
