// src/svelte/components/Section/index.svelte
<script>
	import Blockquote from '../Blockquote/index.svelte';
	import Heading from '../Heading/index.svelte';
	import Image from '../Image/index.svelte';
	import Footnotes from '../Footnotes/index.svelte';
	import HR from '../HR/index.svelte';
	import List from '../List/index.svelte';
	import Paragraph from '../Paragraph/index.svelte';
	import Table from '../Table/index.svelte';
	export let section;
</script>

{#if section.type === 'h3'}
	<Heading type="h3" text={section.text} />

{:else if section.type === 'blockquote'}
	<Blockquote html={section.html} />

{:else if section.type === 'image'}
	<Image src={section.src} alt={section.alt} />

{:else if section.type === 'table'}
	<Table html={section.html} />

{:else if section.type === 'hr'}
	<HR />

{:else if section.type === 'footnotes'}
	<Footnotes footnotes={section.footnotes} />

{:else if section.type === 'list'}
	<List variant={section.variant} items={section.items} />

{:else}
	<Paragraph html={section.html} />
{/if}

// src/vue/components/Section/index.vue
<script setup>
	
	import Blockquote from '../Blockquote/index.vue';
	import Heading from '../Heading/index.vue';
	import Image from '../Image/index.vue';
	import HR from '../HR/index.vue';
	import Footnotes from '../Footnotes/index.vue';
	import List from '../List/index.vue';
	import Paragraph from '../Paragraph/index.vue';
	import Table from '../Table/index.vue';

	defineProps({
		section: {
			type: Object,
			required: true
		}
	});

</script>

<template>
	<Heading v-if="section.type === 'h3'" type="h3" :text="section.text" />
	<Blockquote v-else-if="section.type === 'blockquote'" :html="section.html" />
	<Image v-else-if="section.type === 'image'" :src="section.src" :alt="section.alt" />
	<Table v-else-if="section.type === 'table'" :html="section.html" />
	<HR v-else-if="section.type === 'hr'" />
	<Footnotes v-else-if="section.type === 'footnotes'" :footnotes="section.footnotes" />
	<List v-else-if="section.type === 'list'" :variant="section.variant" :items="section.items" />
	<Paragraph v-else :html="section.html" />
</template>
