// src/vue/layouts/Home/index.vue
<script setup>
	
	import Entries from '../../components/Entries/index.vue';
	import FooterComponent from '../../components/Footer/index.vue';
	import HeaderComponent from '../../components/Header/index.vue';

	defineProps({
		data: {
			type: Object,
			required: true
		}
	});

</script>

<template>
	<HeaderComponent />
	<Entries :entries="data.entries" />
	<FooterComponent />
</template>

// src/preact/layouts/Home/index.jsx
/* eslint-disable no-unused-vars */
import { Fragment } from 'preact';

import Entries from '../../components/Entries';
import Footer from '../../components/Footer';
import Header from '../../components/Header';

/**
 * Home
 *
 * @export
 * @param {object} Journal data
 * @return {string}
 */
export default function Home({ data }) {
	const { entries } = data;
	return (
		<Fragment>
			<Header />
			<Entries entries={entries} />
			<Footer />
		</Fragment>
	);
}
