// src/vue/components/Content/index.vue
<script setup>

	import Section from '../Section/index.vue';

	import style from './style.module.css';

	defineProps({
		body: {
			type: Object,
			required: true
		}
	});

</script>

<template>
	<div :class="style.content">
		<template v-for="section in body" :key="section.id">
			<Section :section="section" />
		</template>
	</div>
</template>

// src/preact/components/Content/index.jsx
/* eslint-disable no-unused-vars */
import { h } from 'preact';

import Section from '../Section';

import style from './style.module.css';

export default function Content({ body }) {
	return (
		<div class={style.content}>
			{body.map(section => {
				return <Section key={section.id} section={section} />;
			})}
		</div>
	);
}
