// src/preact/components/Section/index.jsx
import Blockquote from '../Blockquote';
import Heading from '../Heading';
import Image from '../Image';
import HR from '../HR';
import Footnotes from '../Footnotes';
import List from '../List';
import Paragraph from '../Paragraph';
import Table from '../Table';

function format(section) {
	switch (section.type) {
		case 'h3': return <Heading level="h3" type="h3" text={section.text} />;
		case 'blockquote': return <Blockquote html={section.html} />;
		case 'image': return <Image src={section.src} alt={section.alt} />;
		case 'table': return <Table html={section.html} />;
		case 'hr': return <HR />;
		case 'footnotes': return <Footnotes footnotes={section.footnotes} />;
		case 'list': return <List variant={section.variant} items={section.items} />;
		default: return <Paragraph html={section.html} />;
	}
}

export default function Section({ section }) {
	return format(section);
}

// src/svelte/components/Section/index.svelte
<script>
	import Blockquote from '../Blockquote/index.svelte';
	import Heading from '../Heading/index.svelte';
	import Image from '../Image/index.svelte';
	import Footnotes from '../Footnotes/index.svelte';
	import HR from '../HR/index.svelte';
	import List from '../List/index.svelte';
	import Paragraph from '../Paragraph/index.svelte';
	import Table from '../Table/index.svelte';
	export let section;
</script>

{#if section.type === 'h3'}
	<Heading type="h3" text={section.text} />

{:else if section.type === 'blockquote'}
	<Blockquote html={section.html} />

{:else if section.type === 'image'}
	<Image src={section.src} alt={section.alt} />

{:else if section.type === 'table'}
	<Table html={section.html} />

{:else if section.type === 'hr'}
	<HR />

{:else if section.type === 'footnotes'}
	<Footnotes footnotes={section.footnotes} />

{:else if section.type === 'list'}
	<List variant={section.variant} items={section.items} />

{:else}
	<Paragraph html={section.html} />
{/if}
