// src/preact/components/Image/index.jsx
/* eslint-disable no-unused-vars */
import { h } from 'preact';

import style from './style.module.css';

export default function Image({ src, alt }) {
	return (
		<div class={style.imageContainer}>
			<img
				class={style.image}
				width="800px"
				height="500px"
				src={src}
				alt={alt}
			/>
		</div>
	);
}

// src/vue/components/Image/index.vue
<script setup>

	import style from './style.module.css';

	defineProps({
		src: {
			type: String,
			required: true
		},
		alt: {
			type: String,
			required: true
		}
	});

</script>

<template>
	<div :class="style.imageContainer">
		<img
			:class="style.image"
			width="800px"
			height="500px"
			:src="src"
			:alt="alt"
		>
	</div>
</template>
