// src/vue/components/List/index.vue
<script setup>
	
	import ListItem from '../ListItem/index.vue';

	defineProps({
		items: {
			type: Array,
			required: true
		},
		variant: {
			type: String,
			required: true
		}
	});

</script>

<template>
	<ul v-if="variant === 'unordered'">
		<template v-for="item in items" :key="item.id">
			<ListItem :item="item" />
		</template>
	</ul>
	<ol v-else-if="variant === 'ordered'">
		<template v-for="item in items" :key="item.id">
			<ListItem :item="item" />
		</template>
	</ol>
</template>

// src/svelte/components/List/index.svelte
<script>
	import ListItem from '../ListItem/index.svelte';
	export let items;
	export let variant;
</script>

{#if variant === 'unordered'}
<ul>
	{#each items as item}
		<ListItem html={item.html} />
	{/each}
</ul>
{:else}
<ol>
	{#each items as item}
		<ListItem html={item.html} />
	{/each}
</ol>
{/if}
