// src/preact/components/List/index.jsx
import ListItem from '../ListItem';

export default function List({ variant, items }) {
	if (variant === 'unordered') {
		return (
			<ul>
				{items.map(item => <ListItem key={item.id} html={item.html} />)}
			</ul>
		);
	}
	return (
		<ol>
			{items.map(item => <ListItem key={item.id} html={item.html} />)}
		</ol>
	);
}

// src/svelte/components/List/index.svelte
<script>
	import ListItem from '../ListItem/index.svelte';
	export let items;
	export let variant;
</script>

{#if variant === 'unordered'}
<ul>
	{#each items as item}
		<ListItem html={item.html} />
	{/each}
</ul>
{:else}
<ol>
	{#each items as item}
		<ListItem html={item.html} />
	{/each}
</ol>
{/if}
