// src/preact/components/Entries/index.jsx
/* eslint-disable no-unused-vars */
import { h } from 'preact';

import Entry from '../Entry';

import style from './style.module.css';

export default function Entries({ entries }) {
	return (
		<main class={style.entries}>
			{entries.map(entry => {
				return <Entry key={entry.id} entry={entry} />;
			})}
		</main>
	);
}

// src/vue/components/Entries/index.vue
<script setup>

	import Entry from '../Entry/index.vue';
	
	import style from './style.module.css';
	
	defineProps({
		entries: {
			type: Array,
			required: true
		}
	});

</script>

<template>
	<main :class="style.entries">
		<template v-for="entry in entries" :key="entry.id">
			<Entry :entry="entry" />
		</template>
	</main>
</template>
