// src/preact/components/Heading/index.jsx
/* eslint-disable no-unused-vars */
import { h } from 'preact';

import style from './style.module.css';

/**
 * Heading
 *
 * @param {object} props
 * @return {string}
 */
function Heading(props) {

	const {
		link,
		level,
		type = level,
		text
	} = props;

	if (level === 'h1') {
		return <h1 class={style[type]} id={link && link}>{text}</h1>;
	}

	if (level === 'h2') {
		return <h2 class={style[type]} id={link && link}>{text}</h2>;
	}

	if (level === 'h3') {
		return <h3 class={style[type]} id={link && link}>{text}</h3>;
	}

	if (level === 'h4') {
		return <h4 class={style[type]} id={link && link}>{text}</h4>;
	}

	return null;

}

export default Heading;

// src/svelte/components/Heading/index.svelte
<script>
	import style from './style.module.css';
	export let type;
	export let link = undefined;
	export let text;
</script>

{#if type === 'h1'}
	<h1 class={style[type]} id={link && link}>{text}</h1>
{/if}

{#if type === 'h2'}
	<h2 class={style[type]} id={link && link}>{text}</h2>
{/if}

{#if type === 'h3'}
	<h3 class={style[type]} id={link && link}>{text}</h3>
{/if}

{#if type === 'h4'}
	<h4 class={style[type]} id={link && link}>{text}</h4>
{/if}

{#if type === 'date'}
	<h4 class={style[type]} id={link && link}>{text}</h4>
{/if}
