// src/vue/components/Tags/index.vue
<script setup>

	import Tag from '../Tag/index.vue';
	import Heading from '../Heading/index.vue';
	import style from './style.module.css';

	defineProps({
		tags: {
			type: Array,
			required: true
		}
	});

</script>

<template>
	<section :class="style.tagContainer">
		<Heading level="h3" type="h3" text="Tags" />
		<ul :class="style.tags">
			<template v-for="tag in tags" :key="tag.id">
				<Tag :tag="tag" :number-of-tags="tags.length" />
			</template>
		</ul>
	</section>
</template>

// src/svelte/components/Tags/index.svelte
<script>
	import Heading from '../Heading/index.svelte';
	import Tag from '../Tag/index.svelte';
	import style from './style.module.css';
	export let tags;
</script>

<section class={style.tagContainer}>
	<Heading type="h3" text="Tags" />
	<ul class={style.tags}>
		{#each tags as tag}
			<Tag tag={tag} number={tags.length} />
		{/each}
	</ul>
</section>
